openapi: 3.0.3
info:
  description: Description price service API
  version: 1.0.1
  title: Prices service API
servers:
  - url: http://localhost:8080
tags:
  - name: Prices
paths:
  /prices/{brandId}/{productId}/{date}:
    $ref: "api-paths/v1/prices-api-v1.yaml#/prices"


